# -*- coding: utf-8 -*-
"""ARS - I Final

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bw_koi4TaydrDjbFECTXKa8e0ixt0lUH
"""

import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
from transformers import BertTokenizer
import torch
from sklearn.model_selection import train_test_split
from transformers import BertForSequenceClassification
from torch.optim import AdamW # Corrected import
from torch.utils.data import TensorDataset, DataLoader, RandomSampler, SequentialSampler
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
import time
import datetime

#1 Load dataset
# import pandas as pd

df = pd.read_csv('dataset.csv')
df.head()

#2 Data Preprocessing
# import re
# import nltk
# from nltk.corpus import stopwords
# from sklearn.preprocessing import LabelEncoder

# Download stopwords if not already downloaded
try:
    stopwords.words('english')
except LookupError:
    nltk.download('stopwords')

stop_words = set(stopwords.words('english'))

def clean_text(text):
    """Cleans the text data."""
    if isinstance(text, str):
        # Convert to lowercase
        text = text.lower()
        # Remove special characters and punctuation
        text = re.sub(r'[^a-zA-Z\s]', '', text)
        # Tokenize the text
        tokens = text.split()
        # Remove stop words
        tokens = [word for word in tokens if word not in stop_words]
        # Join tokens back into a string
        cleaned_text = ' '.join(tokens)
        return cleaned_text
    return "" # Return empty string for non-string inputs

# Apply the cleaning function to the 'Resume' and 'Job_Description' columns
df['cleaned_resume'] = df['Resume'].apply(clean_text)
df['cleaned_job_description'] = df['Job_Description'].apply(clean_text)

# Preprocess the 'Decision' column (target variable)
label_encoder = LabelEncoder()
df['Decision_Encoded'] = label_encoder.fit_transform(df['Decision'])

# Display the first few rows with the new cleaned and encoded columns
df[['Resume', 'cleaned_resume', 'Job_Description', 'cleaned_job_description', 'Decision', 'Decision_Encoded']].head()

#3 Feature Engineering
# from sklearn.feature_extraction.text import TfidfVectorizer
# from sklearn.metrics.pairwise import cosine_similarity
# from sklearn.model_selection import train_test_split

# Combine cleaned resume and job description for TF-IDF vectorization
# This ensures the vocabulary is built from both sets of text
combined_text = df['cleaned_resume'].tolist() + df['cleaned_job_description'].tolist()

# Initialize and fit TF-IDF Vectorizer on the combined text
tfidf_vectorizer = TfidfVectorizer()
tfidf_vectorizer.fit(combined_text)

# Transform cleaned resume and job description separately
tfidf_resume = tfidf_vectorizer.transform(df['cleaned_resume'])
tfidf_job_description = tfidf_vectorizer.transform(df['cleaned_job_description'])

# Calculate cosine similarity between resume and job description TF-IDF vectors
# Reshape tfidf_job_description to a sparse matrix with 1 row for pairwise comparison
similarity_scores = []
for i in range(tfidf_resume.shape[0]):
    resume_vector = tfidf_resume[i]
    job_description_vector = tfidf_job_description[i]
    # Calculate similarity between the resume vector and the job description vector
    similarity = cosine_similarity(resume_vector, job_description_vector)
    similarity_scores.append(similarity[0][0])

# Add the similarity scores as a new feature to the DataFrame
df['resume_job_similarity'] = similarity_scores

# Split data into training and testing sets
# X will be the similarity score feature, y will be the encoded decision
X = df[['resume_job_similarity']]
y = df['Decision_Encoded']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)
X_train.head()

#4 Model Training
# from sklearn.linear_model import LogisticRegression
# from sklearn.ensemble import RandomForestClassifier

# Initialize and train the Logistic Regression model
lr_classifier = LogisticRegression(random_state=42)
lr_classifier.fit(X_train, y_train)

# Initialize and train the Random Forest Classifier model
rf_classifier = RandomForestClassifier(random_state=42)
rf_classifier.fit(X_train, y_train)

print("Logistic Regression Classifier trained.")
print("Random Forest Classifier trained.")

#5 Model Evaluation
# from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

# Evaluate Logistic Regression
y_pred_lr = lr_classifier.predict(X_test)
y_proba_lr = lr_classifier.predict_proba(X_test)[:, 1] # Get probabilities for the positive class

accuracy_lr = accuracy_score(y_test, y_pred_lr)
precision_lr = precision_score(y_test, y_pred_lr)
recall_lr = recall_score(y_test, y_pred_lr)
f1_lr = f1_score(y_test, y_pred_lr)
auc_lr = roc_auc_score(y_test, y_proba_lr)

print("--- Logistic Regression Evaluation ---")
print(f"Accuracy: {accuracy_lr:.4f}")
print(f"Precision: {precision_lr:.4f}")
print(f"Recall: {recall_lr:.4f}")
print(f"F1-score: {f1_lr:.4f}")
print(f"AUC: {auc_lr:.4f}")

# Evaluate Random Forest Classifier
y_pred_rf = rf_classifier.predict(X_test)
y_proba_rf = rf_classifier.predict_proba(X_test)[:, 1] # Get probabilities for the positive class

accuracy_rf = accuracy_score(y_test, y_pred_rf)
precision_rf = precision_score(y_test, y_pred_rf)
recall_rf = recall_score(y_test, y_pred_rf)
f1_rf = f1_score(y_test, y_pred_rf)
auc_rf = roc_auc_score(y_test, y_proba_rf)

print("\n--- Random Forest Classifier Evaluation ---")
print(f"Accuracy: {accuracy_rf:.4f}")
print(f"Precision: {precision_rf:.4f}")
print(f"Recall: {recall_rf:.4f}")
print(f"F1-score: {f1_rf:.4f}")
print(f"AUC: {auc_rf:.4f}")

#6 Model Comparison
print("--- Comparing Model Performance (Logistic Regression vs. Random Forest Classifier) ---")
print(f"Logistic Regression:")
print(f"  Accuracy: {accuracy_lr:.4f}")
print(f"  Precision: {precision_lr:.4f}")
print(f"  Recall: {recall_lr:.4f}")
print(f"  F1-score: {f1_lr:.4f}")
print(f"  AUC: {auc_lr:.4f}")

print("\nRandom Forest Classifier:")
print(f"  Accuracy: {accuracy_rf:.4f}")
print(f"  Precision: {precision_rf:.4f}")
print(f"  Recall: {recall_rf:.4f}")
print(f"F1-score: {f1_rf:.4f}")
print(f"  AUC: {auc_rf:.4f}")

# Prepare data for bert
# from transformers import BertTokenizer
# import torch
# from sklearn.model_selection import train_test_split

# Load BERT tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

# Define maximum sequence length
MAX_LEN = 512 # BERT's maximum input length

# Tokenize and create input sequences
input_ids = []
attention_masks = []
token_type_ids = []

for index, row in df.iterrows():
    encoded_dict = tokenizer.encode_plus(
        row['cleaned_resume'],      # Resume text
        row['cleaned_job_description'], # Job description text
        add_special_tokens = True,  # Add '[CLS]' and '[SEP]'
        max_length = MAX_LEN,       # Pad or truncate
        padding = 'max_length',   # Pad to max length
        truncation=True,         # truncate long sequences
        return_attention_mask = True, # Construct attention mask
        return_token_type_ids = True, # Construct token type IDs
        return_tensors = 'pt',      # Return pytorch tensors
    )

    input_ids.append(encoded_dict['input_ids'])
    attention_masks.append(encoded_dict['attention_mask'])
    token_type_ids.append(encoded_dict['token_type_ids'])

# Concatenate the tensors
input_ids = torch.cat(input_ids, dim=0)
attention_masks = torch.cat(attention_masks, dim=0)
token_type_ids = torch.cat(token_type_ids, dim=0)
labels = torch.tensor(df['Decision_Encoded'].values)


# Split data into training and testing sets
train_inputs, validation_inputs, train_labels, validation_labels = train_test_split(
    input_ids, labels, random_state=42, test_size=0.2)

train_masks, validation_masks, _, _ = train_test_split(
    attention_masks, labels, random_state=42, test_size=0.2)

train_token_types, validation_token_types, _, _ = train_test_split(
    token_type_ids, labels, random_state=42, test_size=0.2)

print("Shape of train_inputs:", train_inputs.shape)
print("Shape of validation_inputs:", validation_inputs.shape)
print("Shape of train_labels:", train_labels.shape)
print("Shape of validation_labels:", validation_labels.shape)

# Train BERT model
# from transformers import BertForSequenceClassification
# from torch.optim import AdamW # Corrected import
# from torch.utils.data import TensorDataset, DataLoader, RandomSampler, SequentialSampler
# import numpy as np
# from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
# import time
# import datetime

# Create the DataLoader for our training set
train_data = TensorDataset(train_inputs, train_masks, train_token_types, train_labels)
train_sampler = RandomSampler(train_data)
train_dataloader = DataLoader(train_data, sampler=train_sampler, batch_size=16) # Increased batch size to 16

# Create the DataLoader for our validation set
validation_data = TensorDataset(validation_inputs, validation_masks, validation_token_types, validation_labels)
validation_sampler = SequentialSampler(validation_data)
validation_dataloader = DataLoader(validation_data, sampler=validation_sampler, batch_size=16) # Increased batch size to 16

# Load BertForSequenceClassification, the pretrained BERT model with a single linear classification layer on top.
model = BertForSequenceClassification.from_pretrained(
    "bert-base-uncased", # Use the 12-layer BERT model, with an uncased vocab.
    num_labels = 2, # The number of output labels--2 for binary classification.
                    # You can increase this for multi-class tasks.
    output_attentions = False, # Whether the model returns attentions weights.
    output_hidden_states = False, # Whether the model returns all hidden-states.
)

# Tell pytorch to run this model on the GPU.
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

# Get class weights for imbalanced dataset
class_weights = (len(train_labels) / (2 * np.bincount(train_labels.cpu().numpy())))
class_weights = torch.tensor(class_weights, dtype=torch.float).to(device)

# Optimizer for the model
optimizer = AdamW(model.parameters(),
                  lr = 2e-5, # learning rate
                  eps = 1e-8 # epsilon
                )

# Number of training epochs. I'll stick with 4 for now.
epochs = 5 # Increased epochs to 5

# Total number of training steps is number of batches * number of epochs.
total_steps = len(train_dataloader) * epochs

# Create the learning rate scheduler.
from transformers import get_linear_schedule_with_warmup

scheduler = get_linear_schedule_with_warmup(optimizer,
                                            num_warmup_steps = 500, # Added warmup steps
                                            num_training_steps = total_steps)

# Function to calculate the accuracy of our predictions vs labels
def flat_accuracy(preds, labels):
    pred_flat = np.argmax(preds, axis=1).flatten()
    labels_flat = labels.flatten()
    return np.sum(pred_flat == labels_flat) / len(labels_flat)

# Function to format elapsed times
def format_time(elapsed):
    '''
    Takes a time in seconds and returns a string hh:mm:ss
    '''
    # Round to the nearest second.
    elapsed_rounded = int(round((elapsed)))

    # Format as hh:mm:ss
    return str(datetime.timedelta(seconds=elapsed_rounded))

# Training loop
total_t0 = time.time()

# For each epoch...
for epoch_i in range(0, epochs):

    # ========================================
    #               Training
    # ========================================

    # Perform one full pass over the training set.
    print("")
    print('======== Epoch {:} / {:} ========'.format(epoch_i + 1, epochs))
    print('Training...')

    # Measure how long the training epoch takes.
    t0 = time.time()

    # Reset the total loss for this epoch.
    total_train_loss = 0

    # Put the model into training mode. Don't be mislead--the call to
    # `train` just changes the *mode*, it doesn't *perform* the training.
    # `dropout` and `batchnorm` layers behave differently during training
    # vs. evaluation.
    model.train()

    # For each batch of training data...
    for step, batch in enumerate(train_dataloader):

        # Progress update every 40 batches.
        if step % 40 == 0 and not step == 0:
            # Calculate elapsed time in minutes.
            elapsed = format_time(time.time() - t0)

            # Report progress.
            print('  Batch {:>5,}  of  {:>5,}.    Elapsed: {:}.'.format(step, len(train_dataloader), elapsed))

        # Unpack this training batch from our dataloader.
        #
        # As unpacked here, their item order is:
        #   [0]: input ids
        #   [1]: attention masks
        #   [2]: token type ids
        #   [3]: labels
        b_input_ids = batch[0].to(device)
        b_input_mask = batch[1].to(device)
        b_token_type_ids = batch[2].to(device)
        b_labels = batch[3].to(device)

        # Always clear any previously calculated gradients before performing a backward pass.
        model.zero_grad()

        # Perform a forward pass (evaluate the model on this training batch).
        # The documentation for this `model` function is here:
        # https://huggingface.co/transformers/v2.2.0/model_doc/bert.html#transformers.BertForSequenceClassification
        # It returns different things depending on what it's being asked to do.
        # For classification, it returns the logits for the batch.
        outputs = model(b_input_ids,
                        token_type_ids=b_token_type_ids,
                        attention_mask=b_input_mask,
                        labels=b_labels)

        loss = outputs.loss
        logits = outputs.logits

        # Apply class weights to the loss
        loss = loss * class_weights[b_labels]
        loss = torch.mean(loss)

        # Accumulate the training loss over all of the batches so that we can
        # calculate the average loss at the end. `loss` is a Tensor containing a
        # single value; the `.item()` function returns the Python number from the Tensor.
        total_train_loss += loss.item()

        # Perform a backward pass to calculate the gradients.
        loss.backward()

        # Clip the norm of the gradients to 1.0.
        # This is to help prevent the "exploding gradients" problem.
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)

        # Perform a single optimizer step (parameter update).
        optimizer.step()

        # Update the learning rate.
        scheduler.step()

    # Calculate the average loss over the training data.
    avg_train_loss = total_train_loss / len(train_dataloader)

    # Measure how long this epoch took.
    training_time = format_time(time.time() - t0)

    print("")
    print("  Average training loss: {0:.2f}".format(avg_train_loss))
    print("  Training epoch took: {:}".format(training_time))

    # ========================================
    #               Validation
    # ========================================
    # After the completion of each training epoch, measure our performance on
    # our validation set.

    print("")
    print("Running Validation...")

    t0 = time.time()

    # Put the model in evaluation mode--the dropout layers behave differently
    # during evaluation.
    model.eval()

    # Tracking variables
    total_eval_accuracy = 0
    total_eval_loss = 0
    nb_eval_steps = 0

    # Evaluate data for one epoch
    for batch in validation_dataloader:

        # Unpack this training batch from our dataloader.
        #
        # As unpacked here, their item order is:
        #   [0]: input ids
        #   [1]: attention masks
        #   [2]: token type ids
        #   [3]: labels
        b_input_ids = batch[0].to(device)
        b_input_mask = batch[1].to(device)
        b_token_type_ids = batch[2].to(device)
        b_labels = batch[3].to(device)

        # Tell pytorch not to compute gradients during our forward pass,
        # since this is only needed for training.
        with torch.no_grad():

            # Forward pass, calculate logit predictions.
            # token_type_ids is the same as the "segment ids" in the BERT paper.
            outputs = model(b_input_ids,
                            token_type_ids=b_token_type_ids,
                            attention_mask=b_input_mask,
                            labels=b_labels) # The "labels" are only used for calculating the loss

            loss = outputs.loss
            logits = outputs.logits

        # Accumulate the validation loss.
        total_eval_loss += loss.item()

        # Move logits and labels to CPU
        logits = logits.detach().cpu().numpy()
        label_ids = b_labels.to('cpu').numpy()

        # Calculate the accuracy for this batch of eval samples.
        total_eval_accuracy += flat_accuracy(logits, label_ids)


    # Report the final accuracy for this validation run.
    avg_val_accuracy = total_eval_accuracy / len(validation_dataloader)
    print("  Accuracy: {0:.2f}".format(avg_val_accuracy))

    # Calculate the average loss over the validation data.
    avg_val_loss = total_eval_loss / len(validation_dataloader)

    # Measure how long the validation run took.
    validation_time = format_time(time.time() - t0)

    print("  Validation Loss: {0:.2f}".format(avg_val_loss))
    print("  Validation took: {:}".format(validation_time))

print("")
print("Training complete!")
print("Total training took {:} (h:mm:ss)".format(format_time(time.time()-total_t0)))

# Evaluate BERT model
model.eval()

# Tracking variables
predictions = []
true_labels = []

# Predict
for batch in validation_dataloader:
    # Add batch to device
    batch = tuple(t.to(device) for t in batch)

    # Unpack the batch
    b_input_ids, b_input_mask, b_token_type_ids, b_labels = batch

    # Telling the model not to compute gradients is slightly faster
    with torch.no_grad():
        # Forward pass, calculate logit predictions
        outputs = model(b_input_ids,
                        token_type_ids=b_token_type_ids,
                        attention_mask=b_input_mask)

    logits = outputs.logits

    # Move logits and labels to CPU
    logits = logits.detach().cpu().numpy()
    label_ids = b_labels.to('cpu').numpy()

    # Store predictions and true labels
    predictions.append(logits)
    true_labels.append(label_ids)

# Concatenate the predictions and true labels
predictions = np.concatenate(predictions, axis=0)
true_labels = np.concatenate(true_labels, axis=0)

# Calculate evaluation metrics
predicted_classes = np.argmax(predictions, axis=1)

accuracy = accuracy_score(true_labels, predicted_classes)
precision = precision_score(true_labels, predicted_classes)
recall = recall_score(true_labels, predicted_classes)
f1 = f1_score(true_labels, predicted_classes)
auc = roc_auc_score(true_labels, predictions[:, 1]) # AUC needs probabilities of the positive class

print("--- BERT Model Evaluation ---")
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-score: {f1:.4f}")
print(f"AUC: {auc:.4f}")

import matplotlib.pyplot as plt
import numpy as np

# Model names
models = ['Logistic Regression', 'Random Forest', 'BERT']

# Metrics for each model (replace with your actual evaluation results)
accuracy_scores = [accuracy_lr, accuracy_rf, accuracy]
precision_scores = [precision_lr, precision_rf, precision]
recall_scores = [recall_lr, recall_rf, recall]
f1_scores = [f1_lr, f1_rf, f1]
auc_scores = [auc_lr, auc_rf, auc]

# Create a DataFrame for easier plotting
comparison_df = pd.DataFrame({
    'Model': models,
    'Accuracy': accuracy_scores,
    'Precision': precision_scores,
    'Recall': recall_scores,
    'F1-score': f1_scores,
    'AUC': auc_scores
})

# Plotting the comparison
fig, axes = plt.subplots(nrows=2, ncols=3, figsize=(18, 10))
fig.suptitle('Model Performance Comparison', fontsize=16)

metrics = ['Accuracy', 'Precision', 'Recall', 'F1-score', 'AUC']
y_limits = {'Accuracy': [0, 1], 'Precision': [0, 1], 'Recall': [0, 1], 'F1-score': [0, 1], 'AUC': [0, 1]} # Set y-axis limits for better comparison

axes = axes.flatten() # Flatten the axes array for easy iteration

for i, metric in enumerate(metrics):
    axes[i].bar(comparison_df['Model'], comparison_df[metric], color=['skyblue', 'lightgreen', 'salmon'])
    axes[i].set_ylabel(metric)
    axes[i].set_title(f'{metric} Comparison')
    axes[i].set_ylim(y_limits[metric]) # Apply y-axis limits
    axes[i].tick_params(axis='x', rotation=45)

# Hide the unused subplot
fig.delaxes(axes[5])

plt.tight_layout(rect=[0, 0.03, 1, 0.95]) # Adjust layout to prevent title overlap
plt.show()

# --- Export the BERT Model ---
print("\n--- Exporting BERT Model ---")

# Define the path to save the model
model_export_path = "bert_model.pt" # Using .pt for PyTorch models

# Save the model's state dictionary
torch.save(model.state_dict(), model_export_path)

print(f"✅ BERT model saved to: {model_export_path}")